### PR TITLE
addressing intellij and tee console issue

### PR DESCRIPTION
**Pull request by andruhon**
Addressing #47
Essentially the same, but works in intellij

### CODE REVIEW

**Comment by jprichardson** [comment]
Awesome, thanks. But why does this work, but the other does not?

**Comment by jprichardson** [comment]
Also, does this break anything else?

**Comment by andruhon** [comment]
I presume that it is a defect either in electron, chromium or nodejs, but I'm not sure where to report it.
Normally it should do absolutely the same as `{ stdio: [process.stdin, process.stdout, 'pipe'] }`, tests from /test passing.

**Comment by jprichardson** [comment]
Published, thanks for your help!

**Pull request merged**
