### PR TITLE
Use remote.app if app is not available.

### PR DESCRIPTION
**Pull request by Glinkis**

### CODE REVIEW

**Comment by inukshuk** [comment]
Hi, thanks for contributing! Can you explain the motivation behind this PR?

**Comment by Glinkis** [comment]
`app` is not always available, depending on the context electron is running in, so in those cases it seems to be best practice to use `remote.app`instead.

**Comment by inukshuk** [comment]
This runs only in the main process; in which context would app not be available?

**Comment by Glinkis** [comment]
If I try to run it in the vscode extension `node-tdd` for example, it cannot find `app`, in the same file I now added `remote.app`.

**Comment by Glinkis** [comment]
After all, this does not seem to fix my problem...

```
/Projects/Webb/reverse-image-finder/node_modules/electron-mocha/index.js:22
const app = defaultApp || remote.app
                          ^

ReferenceError: remote is not defined
    at Object.<anonymous> (/Projects/Webb/reverse-image-finder/node_modules/electron-mocha/index.js:22:27)
    at Object.<anonymous> (/Projects/Webb/reverse-image-finder/node_modules/electron-mocha/index.js:126:3)
    at Module._compile (module.js:642:30)
    at Object.Module._extensions..js (module.js:653:10)
    at Module.load (module.js:561:32)
    at tryModuleLoad (module.js:504:12)
    at Function.Module._load (module.js:496:3)
    at Function.Module.runMain (module.js:683:10)
    at startup (bootstrap_node.js:196:16)
    at bootstrap_node.js:622:3
npm ERR! Test failed.  See above for more details.
```

**Comment by inukshuk** [comment]
OK, well, I'm not using VSCode myself, but since VSCode is itself an Electron app it is likely that extension code runs in a Renderer process. Therefore, if you required the electron-mocha module there somehow, it would indeed be possible to import `remote` and that might help you work around errors when importing. That said, however, this is most certainly not what you'd want to do.

**Comment by Glinkis** [comment]
All right, I will close this pull request then.

**Pull request closed without merging**
