### PR TITLE
Electron demo app + tests (for main and renderer)

### PR DESCRIPTION
**Pull request by madarche**
Here is the PR for #35. I've tried my best on this. TODOs and failing tests indicate the points I don't know how to tackle with electron-mocha.

### CODE REVIEW

**Comment by rgbkrk** [comment]
Super cool. Might as well test this app on Travis if that gets configured.

**Comment by madarche** [comment]
@jprichardson have you had the time to look at this PR? What do you think about it?

It raises the question of how to test a renderer view and not just a renderer script. From what I've understood of electron-mocha code there is nothing, as of now, that can be used to load a renderer view. Do you think electron-mocha could modified/extended to deal with this use case? Would you be willing to? I could spend some time on this should you agree and give some directions on how you would like it to be.

Thanks!

**Comment by madarche** [comment]
But I also might be totally wrong on how testing a renderer view is to be done. In this case this PR should be amended to show how.

**Comment by inukshuk** [comment]
Hi @madarche is this still something you would like to see merged? I am sure this can be helpful, but I think it might be a better idea to put this into a separate repository where it can be maintained separately (or at least pinned to a specific electron-mocha release so we don't have to worry about breaking anything).

(Also, I'm not sure what you mean by 'renderer view' exactly)

**Comment by madarche** [comment]
@inukshuk: there is definitely is a need for such an example. But will people find it if we put it outside this repository? Maybe just a BIG WARNING at the top of `examples/electron-demo-app/README.md` stating against which version this example has been validated could do the job? Nevertheless I think the main issue is that this demo app doesn't manage/show how to interact and test the renderer views of an Electron app. Even with your last work (cool! :-) ) on electron-mocha it still seems impossible.

Conclusion: What I would prefer is that this PR is merged and that we try to find a way to test the UI of an Electron app. I can contribute but I need guidance/directions along which to think. But if you want to close this PR and indicate an alternative repo where this demo-app could be merged/put it's fine. Just tell. Thank you!

**Comment by madarche** [comment]
By 'renderer view' I mean a part of the UI of an Electron App, that is an HTML page as spawn by the Main process through a Renderer process (typically like `main_window.loadURL(an_html_page_path)`.

For example Atom is an Electron App, and a developer could want to test the menus of this app (for example to test that when the user clicks on the Save menu item the application doesn't crash).

**Comment by inukshuk** [comment]
I think that providing a framework to test Electron views in this sense is probably out of scope for electron-mocha (we just want to 'run Mocha tests in Electron'). However, we should definitely allow for such tests to be built on top of electron-mocha.

Your second suggestion (providing an option to an html file) is the one I was initially thinking about as well. In theory, you could achieve something very similar now, by using `--require` or `--preload` to run a script which replaces the body of the page with the one you would like to test (you can also inject css and so on), right? Alternatively, if we had the proposed `--view` option, we'd have to run the mocha setup in a preload script. While that should work, it wouldn't be a silver bullet either (e.g., what if your Electron view also depends on a preload script?) What I'm trying to say is that testing your view like this probably works already, but it requires you to set everything up before the tests are run; would adding a `--view` option really help that much? My feeling is no, but I'm happy to be convinced otherwise. Just taking the app I'm working on at the moment, I'd still have to write a lot of scaffolding to set everything up, I'm not sure that I'd really benefit from having the `--view` option. What do you think?

The first option is intriguing, too, but I doubt that we could set this up in a generic way either. For instance, what if your app depends on command line parameters to be called? 

Regarding the examples, I don't know what @jprichardson thinks, but I'd prefer this to go into a separate repo or into a gist. We could add a link to the Readme to make sure people looking for examples find it.

**Comment by madarche** [comment]
Thanks a lot @inukshuk for your detailed answer. At first I thought that electron-mocha aim could be to test Electron apps. But as you reminded me: electron-mocha is 'just run Mocha tests in Electron' (which is good too :-) )

Reading you I reach the same conclusions as you, so this PR can safely be closed and I will look for another project that makes it possible to test Electron apps.

Thanks again!

**Comment by madarche** [comment]
As a side note the Introduction "You can now easily test your Electron apps!" in [README.md](https://github.com/jprichardson/electron-mocha/blob/master/README.md) should be changed into something more along the line "It can help testing your Electron apps".

**Comment by inukshuk** [comment]
@madarche have you seen [spectron](https://github.com/electron/spectron) yet? This seems like the best way forward for integration testing.

**Comment by madarche** [comment]
Spectron seems to be exactly what I'm looking for. I wasn't aware of it until now. Thanks a lot @inukshuk for this advice.

**Comment by iffy** [comment]
So if `electron-mocha` isn't for testing an electron app.... what is it for?  I've been torturing myself trying to get spectron to work, but it's so many steps removed from my main process that it's getting to be a pain (to do things like click on a menu item, for instance).  I'd rather run my tests from within the main process.  Is this something `electron-mocha` can do?

**Comment by inukshuk** [comment]
I use `electron-mocha` for *unit* testing an Electron app; you can also use it in `--renderer` mode to test web apps -- but I use for an Electron app. I think the OP was looking mainly for a way to write integration and UI-driven tests for an Electron app, but `electron-mocha` does not provide much help in that regard. Basically, what it does is, it runs mocha in an Electron main or renderer process. This way, you can unit test all the code of your app in the right environment. If you're used to writing unit tests this is probably what you're looking for. Nothing hinders you to write integration tests (i.e., open your entire app in a window and instrument it etc.), but you'd have to do all the legwork yourself.

**Comment by artemave** [comment]
Here is a [little demo project](https://github.com/featurist/full-stack-js-testing-demo) that shows off full stack integration testing (SPA + express + db) with `electron-mocha`.

This may also address the roadmap item re integration testing?

**Pull request closed without merging**
